---
new_page_extension: md
auto_deploy: false
admin_path: "/admin/"
webhook_url: 
sections:
- type: document
  path: _data/nav.yml
  label: Navigation Menu
- type: jekyll-posts
  label: Blog Posts
  create: all
  new_doc_ext: md
- type: jekyll-pages
  label: Pages
  create: all
- type: heading
  label: Individual Pages
- type: document
  path: christmas.md
  label: Christmas Trees
- type: document
  path: perennial.md
  label: Perennial Plants
- type: document
  path: seedlings.md
  label: Organic Vegetable Seedlings
- type: document
  path: about.md
  label: About
- type: document
  path: contact.md
  label: Contact
upload_dir: assets/images
public_path: "/assets/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    -d _site
